### ISSUE TITLE
Query - How does this language model helps in spell correction

### ISSUE THREAD

**Issue by mineshmathew** [joiharalds/rnnicespellchecker#4]
@joiharalds  Hi. Ianded up here looking for spell checkers using RNN/language models. I am familiar with the RNN based language models. I was wondering how this code works as spell checker/corrector.

**Comment by joiharalds** [comment]
Hi. Well it doesn't. We are still working on similar ideas elsewhere but
this particular repo has become kind of a legacy project. I'm sorry I
should probably remove it or state that it is legacy so people don't get
confused.

Best regards, Johann
